baseurl = "http://allan-simon.github.io/blog/"
languageCode = "en-us"
title = "Allan's blog"

[Params]
    Description = "Tips, tricks and random thoughts on Linux/Vim/rust/php/devops"
    author = "Allan SIMON"
    Copyright = "Creative-Common attribution"
